<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentsTableSeeder extends Seeder
{
    public function run()
    {
        $students = [
            [
                'student_id' => '5225610',
                'first_name' => 'Heart',
                'middle_name' => 'Quinones',
                'last_name' => 'Bodiongan',
                'program' => 'BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5213561',
                'first_name' => 'Daryl',
                'middle_name' => 'Tuante',
                'last_name' => 'Dagpin',
                'program' => 'BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '525041',
                'first_name' => 'Donna Mae',
                'middle_name' => 'Doremon',
                'last_name' => 'Rosales',
                'program' => 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT',
                'year_level' => '1st Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5225169',
                'first_name' => 'Jomar',
                'middle_name' => 'Almirante',
                'last_name' => 'Casco',
                'program' => 'BACHELOR OF SCIENCE IN CRIMINOLOGY',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5224770',
                'first_name' => 'danica',
                'middle_name' => 'Baroy',
                'last_name' => 'Pateno',
                'program' => 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5225459',
                'first_name' => 'Kyle',
                'middle_name' => 'Valerio',
                'last_name' => 'Darullo',
                'program' => 'BACHELOR OF SCIENCE IN CRIMINOLOGY',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5240862',
                'first_name' => 'Mark',
                'middle_name' => 'Sacasan',
                'last_name' => 'Sumayang',
                'program' => 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT',
                'year_level' => '2ND Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5224828',
                'first_name' => 'J-Anne Vallery',
                'middle_name' => 'Obsioma',
                'last_name' => 'Loyola',
                'program' => 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5240193',
                'first_name' => 'Renan',
                'middle_name' => 'Sialana',
                'last_name' => 'Nunez',
                'program' => 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT',
                'year_level' => '2nd Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5241186',
                'first_name' => 'Pascual II',
                'middle_name' => '',
                'last_name' => 'Pahuyo',
                'program' => 'BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY',
                'year_level' => '2nd Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5213396',
                'first_name' => 'April Mae',
                'middle_name' => 'Suaso',
                'last_name' => 'Tedera',
                'program' => 'BACHELOR OF SCIENCE IN PUBLIC ADMINISTRATION',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5224560',
                'first_name' => 'Vanisa',
                'middle_name' => 'Lumogdang',
                'last_name' => 'Sagot',
                'program' => 'BACHELOR OF  EARLY CHILDHOOD EDUCATION',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5226230',
                'first_name' => 'Princess',
                'middle_name' => 'Emperador',
                'last_name' => 'Obra',
                'program' => 'BACHELOR OF SCIENCE IN CRIMINOLOGY',
                'year_level' => '4th Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => '5240602',
                'first_name' => 'Elisa Mae Jean',
                'middle_name' => 'Labrigas',
                'last_name' => 'Madron',
                'program' => 'BACHELOR OF EARLY CHILDHOOD EDUCATION',
                'year_level' => '2nd Year',
                'school_year' => '2025-2026',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        foreach ($students as $student) {
            \App\Models\Student::create($student);
        }
    }
}
